/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#111c2d",
        "primary": "#0058be",
        "on-tertiary-container": "#fdfcff",
        "inverse-surface": "#2e3132",
        "inverse-primary": "#adc6ff",
        "primary-container": "#2170e4",
        "surface-bright": "#f8f9fa",
        "secondary-fixed-dim": "#bcc7de",
        "on-surface": "#191c1d",
        "surface-container": "#edeeef",
        "on-secondary-container": "#586377",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed": "#d8e3fb",
        "surface-variant": "#e1e3e4",
        "tertiary-fixed": "#d4e3ff",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#a4c9ff",
        "outline-variant": "#c2c6d6",
        "tertiary": "#005da8",
        "surface-tint": "#005ac2",
        "secondary-container": "#d5e0f8",
        "on-tertiary-fixed-variant": "#004883",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "tertiary-container": "#2676c8",
        "secondary": "#545f73",
        "primary-fixed-dim": "#adc6ff",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#001c39",
        "on-background": "#191c1d",
        "on-surface-variant": "#424754",
        "surface-dim": "#d9dadb",
        "on-primary-fixed": "#001a42",
        "on-error": "#ffffff",
        "outline": "#727785",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fefcff",
        "surface-container-highest": "#e1e3e4",
        "on-primary-fixed-variant": "#004395",
        "on-primary": "#ffffff",
        "surface": "#f8f9fa",
        "background": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "inverse-on-surface": "#f0f1f2"
      }
    },
  },
  plugins: [],
}
